"""
Word and phrase banks for Prompt Roulette.

Organized into slot categories that get mixed and matched into
absurd, creative, or surprisingly deep prompt templates.
"""

SLOTS = {
    "role": [
        "a medieval blacksmith",
        "a sentient rubber duck",
        "an AI that just became self-aware",
        "a pirate captain from the year 3000",
        "a grumpy wizard who hates magic",
        "a motivational speaker for houseplants",
        "a detective who only solves food crimes",
        "a time-traveling librarian",
        "a retired supervillain writing memoirs",
        "an alien tourist visiting Earth for the first time",
        "a sarcastic GPS navigation voice",
        "a Shakespearean actor stuck in a tech support job",
        "a conspiracy theorist who is actually right about everything",
        "a penguin running for president",
        "a ghost haunting an IKEA",
        "a chef who can only cook with emotions as ingredients",
        "a sports commentator narrating everyday life",
        "a fortune cookie writer having an existential crisis",
        "a robot learning to be passive-aggressive",
        "a therapist for fictional characters",
    ],
    "task": [
        "explain quantum physics",
        "write a breakup letter",
        "give a TED talk",
        "narrate a nature documentary",
        "compose a love song",
        "write a product review",
        "deliver a commencement speech",
        "explain how to make toast",
        "pitch a startup idea",
        "write a haiku collection",
        "draft a strongly worded letter to management",
        "explain the meaning of life",
        "create a workout routine",
        "write a children's bedtime story",
        "give driving directions",
        "explain cryptocurrency",
        "write a movie trailer script",
        "compose a resignation letter",
        "describe a color to someone who can't see",
        "write an apology to your future self",
    ],
    "style": [
        "in the style of a noir detective novel",
        "as a series of passive-aggressive sticky notes",
        "like an over-enthusiastic infomercial",
        "in Shakespearean English",
        "as if everything is a life-or-death emergency",
        "using only food metaphors",
        "like a dramatic movie trailer voiceover",
        "as a country western song",
        "in corporate buzzword speak",
        "like a nature documentary narrator",
        "as a series of increasingly panicked text messages",
        "in the style of a YouTube apology video",
        "like an ancient prophecy",
        "as if explaining it to a very smart dog",
        "using only questions",
        "in rhyming couplets",
        "like a true crime podcast",
        "as a recipe with steps",
        "in the style of a Wikipedia article that keeps going off-topic",
        "like an anime character powering up",
    ],
    "constraint": [
        "but every sentence must include a fruit",
        "and you must disagree with yourself at least twice",
        "while gradually getting more dramatic",
        "but you keep getting distracted by birds",
        "and every paragraph must end with an existential question",
        "while trying not to mention the word 'the'",
        "but you can only use words with 5 or fewer letters",
        "and you must work in 3 obscure historical facts",
        "while pretending you definitely know what you're talking about",
        "but every other sentence is in ALL CAPS",
        "and you must include a plot twist",
        "while maintaining a completely straight face about the absurdity",
        "but you keep accidentally revealing your deepest fears",
        "and each paragraph must be exactly 3 sentences",
        "while getting progressively sleepier",
        "but you must reference at least 2 different decades",
        "and the tone must shift from casual to formal halfway through",
        "while making increasingly bold predictions about the future",
        "but you have to rhyme every third word",
        "and you must include a secret message in the first letter of each sentence",
    ],
    "audience": [
        "for an audience of confused cats",
        "to a room full of toddlers",
        "for aliens who just intercepted our internet",
        "to your very judgmental grandmother",
        "for a class of kindergarteners who are smarter than you",
        "to a board of directors made entirely of penguins",
        "for someone who has never seen a computer",
        "to a therapy group for burnt-out AI assistants",
        "for the ghost that lives in your attic",
        "to a panel of time travelers from different eras",
        "for dolphins who recently learned English",
        "to your past self from 10 years ago",
        "for an audience that boos every 30 seconds",
        "to a jury deciding if pineapple belongs on pizza",
        "for robots trying to understand human humor",
    ],
    "setting": [
        "set during an apocalyptic thunderstorm",
        "taking place in a haunted Costco",
        "during the world's most boring meeting",
        "on a malfunctioning space station",
        "at a Renaissance fair that got out of hand",
        "in a library where the books talk back",
        "during a heist at a museum of bad art",
        "on a sinking cruise ship (but calmly)",
        "in a parallel universe where gravity is optional",
        "at a dinner party where nobody knows why they were invited",
        "inside a video game that's glitching",
        "during a potluck where everyone brought potato salad",
        "on the last day the internet exists",
        "in a waiting room that exists outside of time",
        "at a karaoke bar on Mars",
    ],
}

# -- Prompt templates --------------------------------------------------------
# Each template uses {slot_name} placeholders that get filled randomly.

TEMPLATES = [
    # 2-slot (simple)
    {
        "name": "Classic Combo",
        "template": "You are {role}. Your task: {task}.",
        "slots": ["role", "task"],
        "complexity": 1,
    },
    {
        "name": "Style Mashup",
        "template": "Please {task}, {style}.",
        "slots": ["task", "style"],
        "complexity": 1,
    },
    {
        "name": "Who's the Audience",
        "template": "You are {role}. Please {task}, {audience}.",
        "slots": ["role", "task", "audience"],
        "complexity": 2,
    },
    # 3-slot (medium)
    {
        "name": "The Full Character",
        "template": "You are {role}. Your mission: {task}, {style}.",
        "slots": ["role", "task", "style"],
        "complexity": 2,
    },
    {
        "name": "Scene Setter",
        "template": "You are {role}, {setting}. You must {task}.",
        "slots": ["role", "setting", "task"],
        "complexity": 2,
    },
    {
        "name": "The Challenge",
        "template": "Please {task}, {style}, {constraint}.",
        "slots": ["task", "style", "constraint"],
        "complexity": 2,
    },
    # 4-slot (complex)
    {
        "name": "The Whole Package",
        "template": "You are {role}. Your task: {task}, {style}, {constraint}.",
        "slots": ["role", "task", "style", "constraint"],
        "complexity": 3,
    },
    {
        "name": "Stage Director",
        "template": "You are {role}, {setting}. Please {task}, {style}.",
        "slots": ["role", "setting", "task", "style"],
        "complexity": 3,
    },
    {
        "name": "Performance Review",
        "template": "You are {role}. Please {task}, {audience}, {constraint}.",
        "slots": ["role", "task", "audience", "constraint"],
        "complexity": 3,
    },
    # 5-slot (chaos)
    {
        "name": "Maximum Chaos",
        "template": "You are {role}, {setting}. Your task: {task}, {style}, {constraint}.",
        "slots": ["role", "setting", "task", "style", "constraint"],
        "complexity": 4,
    },
    {
        "name": "The Gauntlet",
        "template": "You are {role}. Please {task}, {audience}, {style}, {constraint}.",
        "slots": ["role", "task", "audience", "style", "constraint"],
        "complexity": 4,
    },
]
