#!/usr/bin/env python3
"""
ChatGPT Bingo Card Generator
=============================
Generate bingo cards filled with common ChatGPT-isms and play
interactively in your terminal. No dependencies required.

Run:  python -m ai_bingo
"""

import sys
import os
import random

from .card import generate_card, render_card, check_bingo, CARD_SIZE, FREE_SPACE
from .phrases import PHRASES

# -- ANSI colors -------------------------------------------------------------

USE_COLOR = hasattr(sys.stdout, "isatty") and sys.stdout.isatty()
if os.environ.get("NO_COLOR"):
    USE_COLOR = False


def _c(code, text):
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text


def bold(t):     return _c("1", t)
def red(t):      return _c("91", t)
def green(t):    return _c("92", t)
def yellow(t):   return _c("93", t)
def cyan(t):     return _c("96", t)
def dim(t):      return _c("90", t)
def magenta(t):  return _c("95", t)


# -- Display helpers ----------------------------------------------------------

BANNER = r"""
     _    ___   ____  _                    _
    / \  |_ _| | __ )(_)_ __   __ _  ___ | |
   / _ \  | |  |  _ \| | '_ \ / _` |/ _ \| |
  / ___ \ | |  | |_) | | | | | (_| | (_) |_|
 /_/   \_\___| |____/|_|_| |_|\__, |\___/(_)
                               |___/
"""


def print_banner():
    print(cyan(BANNER))
    print(bold("  ChatGPT Bingo Card Generator"))
    print("  Spot the AI-isms. Mark your card. Get BINGO!\n")


def print_menu():
    print(bold("=== MAIN MENU ===\n"))
    print(f"  {bold('1')}. Generate a new card")
    print(f"  {bold('2')}. Generate a card (with seed)")
    print(f"  {bold('3')}. Play interactive bingo")
    print(f"  {bold('4')}. Browse all phrases by category")
    print(f"  {bold('5')}. Export card to text file")
    print(f"  {bold('Q')}. Quit")
    print()


def show_card(grid, marked=None):
    """Display a rendered bingo card."""
    print()
    print(render_card(grid, marked))
    print()


def browse_phrases():
    """Show all phrases organized by category."""
    print(bold("\n=== PHRASE DATABASE ===\n"))
    for cat, phrases in PHRASES.items():
        print(f"  {yellow(cat.upper())} ({len(phrases)} phrases)")
        for i, phrase in enumerate(phrases, 1):
            print(f"    {i:2}. {phrase}")
        print()
    print(f"  {bold('Total:')} {sum(len(v) for v in PHRASES.values())} phrases across {len(PHRASES)} categories\n")


def export_card(grid):
    """Export a card to a plain-text file."""
    filename = "bingo_card.txt"
    try:
        inp = input(f"  Filename [{filename}]: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return
    if inp:
        filename = inp

    text = render_card(grid)
    # Strip ANSI codes for export
    import re
    text = re.sub(r'\033\[[0-9;]*m', '', text)

    with open(filename, "w") as f:
        f.write("CHATGPT BINGO\n")
        f.write("=" * 40 + "\n\n")
        f.write(text)
        f.write("\n\nGenerated by ChatGPT Bingo Card Generator\n")
        f.write("https://github.com/UberGuidoZ/ChatGPT-shenanigans\n")

    print(f"  {green('Saved to')} {bold(filename)}\n")


def play_interactive(grid):
    """Interactive bingo play mode."""
    marked = set()
    center = CARD_SIZE // 2
    marked.add((center, center))  # Free space

    # Build a lookup for quick cell finding
    cell_map = {}
    for r in range(CARD_SIZE):
        for c in range(CARD_SIZE):
            cell_map[(r, c)] = grid[r][c]

    print(bold("\n=== INTERACTIVE BINGO ===\n"))
    print("  Mark squares as you spot ChatGPT doing its thing!")
    print("  The " + green("FREE SPACE") + " in the center is already marked.\n")
    print(dim("  Commands:"))
    print(dim("    <row>,<col>  — Toggle a square (e.g. '1,3' for row 1, col 3)"))
    print(dim("    list         — Show all squares with coordinates"))
    print(dim("    check        — Check for bingo"))
    print(dim("    card         — Redraw the card"))
    print(dim("    reset        — Clear all marks"))
    print(dim("    quit         — Return to menu"))
    print()

    show_card(grid, marked)

    while True:
        try:
            inp = input(f"{bold('Bingo > ')}").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print()
            break

        if not inp:
            continue

        if inp == "quit" or inp == "q":
            break

        elif inp == "card":
            show_card(grid, marked)

        elif inp == "reset":
            marked = {(center, center)}
            print(f"  {dim('All marks cleared.')}\n")
            show_card(grid, marked)

        elif inp == "list":
            print()
            for r in range(CARD_SIZE):
                for c in range(CARD_SIZE):
                    marker = green("[X]") if (r, c) in marked else dim("[ ]")
                    print(f"  {marker} ({r+1},{c+1}) {grid[r][c]}")
            print()

        elif inp == "check":
            wins = check_bingo(marked)
            if wins:
                print()
                print(green(bold("  *** B-I-N-G-O! ***")))
                for kind, detail in wins:
                    print(green(f"  Winner: {kind} {detail}!"))
                print()
                show_card(grid, marked)
            else:
                filled = len(marked)
                remaining = CARD_SIZE - 1  # rough min needed
                print(f"  {yellow('No bingo yet.')} {filled}/{CARD_SIZE*CARD_SIZE} squares marked.\n")

        elif "," in inp:
            parts = inp.split(",")
            if len(parts) == 2:
                try:
                    r = int(parts[0].strip()) - 1
                    c = int(parts[1].strip()) - 1
                    if 0 <= r < CARD_SIZE and 0 <= c < CARD_SIZE:
                        if r == center and c == center:
                            print(f"  {dim('Free space is always marked!')}\n")
                        elif (r, c) in marked:
                            marked.discard((r, c))
                            print(f"  {dim('Unmarked:')} {grid[r][c]}\n")
                        else:
                            marked.add((r, c))
                            print(f"  {green('Marked:')} {grid[r][c]}")
                            # Auto-check for bingo
                            wins = check_bingo(marked)
                            if wins:
                                print()
                                print(green(bold("  *** B-I-N-G-O! ***")))
                                for kind, detail in wins:
                                    print(green(f"  Winner: {kind} {detail}!"))
                                show_card(grid, marked)
                            print()
                    else:
                        print(f"  {red('Out of range.')} Use 1-{CARD_SIZE} for row and column.\n")
                except ValueError:
                    print(f"  {red('Invalid format.')} Use: row,col (e.g. 2,4)\n")
            else:
                print(f"  {red('Invalid format.')} Use: row,col (e.g. 2,4)\n")

        else:
            print(f"  {dim('Unknown command. Try: <row>,<col> | list | check | card | reset | quit')}\n")


def main():
    print_banner()
    current_grid = None

    while True:
        print_menu()
        try:
            choice = input(bold("Choose > ")).strip().lower()
        except (EOFError, KeyboardInterrupt):
            print(f"\n{dim('Goodbye!')}")
            break

        if choice == "q":
            print(f"\n{dim('I hope this helps! Feel free to ask follow-up questions!')}")
            break

        elif choice == "1":
            current_grid = generate_card()
            print(bold("\n  New card generated!"))
            show_card(current_grid)

        elif choice == "2":
            try:
                seed_input = input("  Enter a seed (name, number, anything): ").strip()
            except (EOFError, KeyboardInterrupt):
                print()
                continue
            if seed_input:
                current_grid = generate_card(seed=seed_input)
                print(bold(f"\n  Card generated with seed: '{seed_input}'"))
                print(dim("  (Same seed = same card. Share with friends!)\n"))
                show_card(current_grid)
            else:
                print(f"  {dim('No seed entered.')}\n")

        elif choice == "3":
            if current_grid is None:
                current_grid = generate_card()
                print(bold("\n  Auto-generated a fresh card for you!"))
            play_interactive(current_grid)

        elif choice == "4":
            browse_phrases()

        elif choice == "5":
            if current_grid is None:
                current_grid = generate_card()
                print(bold("\n  Auto-generated a card for export."))
                show_card(current_grid)
            export_card(current_grid)

        else:
            print(red("  Invalid choice. Try 1-5 or Q.\n"))


if __name__ == "__main__":
    main()
